colunas_imbarq006 = [
    "Tipo Registro",
    "Código Participante Solicitante",
    "Código Investidor Solicitante",
    "Código Participante Solicitado",
    "Código Investidor Solicitado",
    "Data Movimento",
    "Código Instrumento",
    "Código Origem Identificação Instrumento",
    "Código Bolsa Valor",
    "Origem",
    "Número Contrato",
    "Número Contrato Anterior",
    "Natureza Lado Doador Vendedor",
    "Código Instrumento Ativo Objeto",
    "Código Origem Identificação Ativo Objeto",
    "Código Bolsa Valor Ativo Objeto",
    "ISIN Ativo Objeto",
    "Distribuição Ativo Objeto",
    "Mercado",
    "Código Negociação",
    "Data Negociação",
    "Data Vencimento",
    "Data Carência",
    "Código Carteira",
    "Preço Referência Ativo Objeto",
    "Fator",
    "Quantidade Original",
    "Quantidade Em Liquidação",
    "Quantidade Total Títulos Liquidados",
    "Quantidade Coberta",
    "Quantidade Descoberta",
    "Quantidade Renovada",
    "Quantidade Atual",
    "Volume",
    "Tipo Liquidação",
    "Indicador Liquidação Antecipada",
    "Indicador Liquidação Antecipada OPA",
    "Taxa Doadora ou Tomadora",
    "Participante Executor",
    "Investidor Participante Executor",
    "Contraparte Tributária JSCP",
    "Contraparte Tributária Rendimento",
    "Tipo Contrato",
    "Número Instrução Liquidação",
    "Código Custodiante",
    "Código Investidor Custodiante",
    "Quantidade Posição Cobertura à Vista",
    "Tipo Contrato Original",
    "Código Intermediação",
    "Indicador Origem Negociação Eletrônica",
    "Indicador Oferta Certificada Doadora",
    "Vencimento Título",
    "Código Identificador Título SELIC",
    "Percentual Índice Correção",
    "Código Instrumento Índice Correção",
    "Código Origem Índice Correção",
    "Código Bolsa Índice Correção",
    "Preço Título Público Atualizado",
    "Reserva"
]